import { FormEvent, useMemo, useState } from 'react'
import { CareerReadinessPanel } from './components/CareerReadinessPanel'
import { MissionLibrary } from './components/MissionLibrary'
import { MissionPlayer } from './components/MissionPlayer'
import { ProgressPanel } from './components/ProgressPanel'
import { RoadmapView } from './components/RoadmapView'
import { SkillProfileView } from './components/SkillProfileView'
import { TrackCompass } from './components/TrackCompass'
import { TutorPanel } from './components/TutorPanel'
import { getAnyLearningChallenge } from './data/challengeCatalog'
import { diagnosticChallenges } from './data/diagnostic'
import { learningChallenges } from './data/learningChallenges'
import { skills } from './data/skills'
import type { Challenge, CodeLanguage, CodeRunResult, LearnerState, TrackId } from './domain'
import { runCode } from './lib/codeRunner'
import { progressSummary } from './lib/gamification'
import { buildSkillProfile, recommendTracks } from './lib/profile'
import { emptyState, loadState, resetState, saveState } from './lib/progress'
import { buildCareerReadiness } from './lib/readiness'
import { getReviewQueue } from './lib/retention'
import { generateRoadmap } from './lib/roadmap'

type View='dashboard'|'diagnostic'|'profile'|'roadmap'|'missions'|'mission'
const diagnosticIds=new Set(diagnosticChallenges.map((item)=>item.id))

function App(){
  const [view,setView]=useState<View>('dashboard');const [selectedMission,setSelectedMission]=useState<string|null>(null);const [state,setState]=useState<LearnerState>(()=>loadState())
  const profile=useMemo(()=>buildSkillProfile(state),[state]);const recommendations=useMemo(()=>recommendTracks(profile,state.trackInterest),[profile,state.trackInterest]);const roadmap=useMemo(()=>generateRoadmap(profile,state.trackInterest),[profile,state.trackInterest]);const progress=useMemo(()=>progressSummary(state),[state]);const readiness=useMemo(()=>buildCareerReadiness(state,profile),[state,profile]);const dueReviews=useMemo(()=>getReviewQueue(state),[state])
  function update(next:LearnerState){setState(next);saveState(next)}
  function restart(){resetState();setState(emptyState);setView('dashboard')}
  function updateInterest(track:TrackId,value:number){update({...state,trackInterest:{...state.trackInterest,[track]:value}})}
  function openMission(id:string){if(!getAnyLearningChallenge(id))return;setSelectedMission(id);setView('mission')}
  if(view==='diagnostic')return <Diagnostic state={state} onUpdate={update} onExit={()=>setView('dashboard')} onComplete={()=>setView('profile')}/>
  if(view==='profile')return <SkillProfileView profile={profile} onBack={()=>setView('dashboard')} onRoadmap={()=>setView('roadmap')}/>
  if(view==='roadmap')return <RoadmapView weeks={roadmap} onBack={()=>setView('dashboard')} onProfile={()=>setView('profile')} onOpenMission={openMission}/>
  if(view==='missions')return <MissionLibrary state={state} onUpdate={update} onBack={()=>setView('dashboard')} onOpen={openMission}/>
  if(view==='mission'&&selectedMission){const challenge=getAnyLearningChallenge(selectedMission);if(challenge)return <MissionPlayer challenge={challenge} state={state} onUpdate={update} onBack={()=>setView('missions')}/>}

  const diagnosticAttempts=state.attempts.filter((attempt)=>diagnosticIds.has(attempt.challengeId));const diagnosticCompletion=Math.round((diagnosticAttempts.length/diagnosticChallenges.length)*100);const evaluations=Object.values(state.tutor).reduce((sum,item)=>sum+item.evaluations.length,0)
  const completedIds=new Set(state.missionCompletions.map((item)=>item.challengeId));const next=roadmap.flatMap((week)=>week.items).find((item)=>item.kind!=='review'&&!completedIds.has(item.id)&&getAnyLearningChallenge(item.id))??learningChallenges.find((item)=>!completedIds.has(item.id));const evidencedAreas=readiness.filter((area)=>area.status==='evidenced').length
  return <main className="shell">
    <nav className="top-nav"><button className="active">Dashboard</button><button onClick={()=>setView('diagnostic')}>Diagnostic</button><button onClick={()=>setView('missions')}>Engineering gym{dueReviews.length?` · ${dueReviews.length} due`:''}</button><button onClick={()=>setView('profile')}>Skill profile</button><button onClick={()=>setView('roadmap')}>Career roadmap</button></nav>
    <header className="hero"><div><p className="eyebrow">CAREER ALPHA · 0.6</p><h1>SDE <span>→</span> FDE</h1><p className="lede">A hands-on engineering gym for turning practical automation experience into deeper software-engineering capability—and retaining it long enough to use under pressure.</p></div><div className="level-card"><span>Learning evidence</span><strong>{progress.completed}/{progress.total}</strong><small>core missions · {state.reviewCompletions.length} delayed reviews · {evidencedAreas}/8 readiness areas evidenced</small></div></header>
    <ProgressPanel summary={progress}/>
    <section className="north-star card"><div><p className="eyebrow">NORTH STAR</p><h2>Become better at doing engineering, not consuming courses.</h2></div><p>Problem → attempt → failure → hint → discovery → explanation → delayed recall → mastery.</p></section>
    {dueReviews.length>0&&<section className="card due-review-callout"><div><p className="eyebrow">ACTIVE RECALL DUE</p><h2>{dueReviews.length} mission{dueReviews.length===1?'':'s'} need re-proving.</h2><p>Old completion does not count as retained knowledge. Re-solve with fresh evidence before continuing.</p></div><button onClick={()=>setView('missions')}>Open review queue →</button></section>}
    <section className="grid two"><article className="card mission-card"><p className="eyebrow">NEXT RECOMMENDED REP</p><h2>{next?.title??'First four-week cycle complete'}</h2><p>{next?.outcome??'Revisit your skill profile and generate the next learning cycle from new evidence.'}</p>{next&&<div className="row"><span>{next.kind} · {next.minutes??'hands-on'} min</span><button onClick={()=>openMission(next.id)}>Start mission →</button></div>}</article><article className="card"><p className="eyebrow">DIAGNOSTIC BASELINE</p><h2>{diagnosticCompletion}% captured</h2><p>The diagnostic remains separate from ongoing mission progress, so learning reps cannot accidentally inflate the baseline.</p><div className="progress"><i style={{width:`${diagnosticCompletion}%`}}/></div><div className="row"><strong>{diagnosticAttempts.length}/{diagnosticChallenges.length}</strong><button className="ghost" onClick={()=>setView('diagnostic')}>{diagnosticCompletion===100?'Review diagnostic':'Continue'}</button></div>{(diagnosticAttempts.length>0||state.missionCompletions.length>0)&&<button className="reset-link" onClick={restart}>Reset all local progress</button>}</article></section>
    <TrackCompass interest={state.trackInterest} recommendations={recommendations} onChange={updateInterest}/>
    <CareerReadinessPanel state={state} profile={profile}/>
    <section><div className="section-heading"><div><p className="eyebrow">SKILL GRAPH</p><h2>Uneven is expected.</h2></div><p>Every number comes from stored challenge evidence. A dash means we genuinely do not know yet.</p></div><div className="skill-grid">{skills.map((skill)=>{const item=profile.find((entry)=>entry.skillId===skill.id)!;return <article className="skill" key={skill.id}><div className="skill-top"><span>{skill.target}</span><b>{item.mastery===null?'UNKNOWN':`${item.mastery}% · ${item.confidence}% conf.`}</b></div><h3>{skill.name}</h3><p>{skill.description}</p></article>})}</div></section>
  </main>
}

function Diagnostic({state,onUpdate,onExit,onComplete}:{state:LearnerState;onUpdate:(state:LearnerState)=>void;onExit:()=>void;onComplete:()=>void}){
  const index=Math.min(state.currentChallengeIndex,diagnosticChallenges.length-1);const challenge=diagnosticChallenges[index];const previous=state.attempts.find((attempt)=>attempt.challengeId===challenge.id);const language=state.languages[challenge.id]??challenge.coding?.languages[0]??'typescript';const starter=challenge.coding?.starterCode[language]??'';const answer=state.drafts[challenge.id]??previous?.answer??starter;const runs=state.codeRuns[challenge.id]??[];const [running,setRunning]=useState(false);const finished=state.currentChallengeIndex>=diagnosticChallenges.length
  if(finished){const diagnosticAttempts=state.attempts.filter((attempt)=>diagnosticIds.has(attempt.challengeId));const objective=diagnosticAttempts.filter((attempt)=>typeof attempt.objectiveCorrect==='boolean');const correct=objective.filter((attempt)=>attempt.objectiveCorrect).length;const codeRuns=Object.values(state.codeRuns).flat().filter((run)=>diagnosticIds.has(run.challengeId));const passingRuns=codeRuns.filter((run)=>run.status==='passed').length;const tutorReviews=Object.entries(state.tutor).filter(([id])=>diagnosticIds.has(id)).reduce((sum,[,item])=>sum+item.evaluations.length,0);return <main className="shell diagnostic-shell"><button className="back" onClick={onExit}>← Dashboard</button><section className="card finish"><p className="eyebrow">BASELINE · EVIDENCE CAPTURED</p><h1>Diagnostic attempt complete.</h1><p>You completed all {diagnosticChallenges.length} diagnostic challenges.</p><div className="score-row"><div><strong>{correct}/{objective.length}</strong><span>objective checks</span></div><div><strong>{passingRuns}</strong><span>passing code runs</span></div><div><strong>{tutorReviews}</strong><span>tutor evaluations</span></div></div><p className="note">Your baseline distinguishes mastery from evidence confidence and exposes exactly what evidence each skill value came from.</p><button onClick={onComplete}>Open my baseline →</button></section></main>}
  function setAnswer(value:string){onUpdate({...state,drafts:{...state.drafts,[challenge.id]:value}})}
  function setLanguage(nextLanguage:CodeLanguage){const currentStarter=challenge.coding?.starterCode[language];const shouldReplace=!state.drafts[challenge.id]||state.drafts[challenge.id]===currentStarter;onUpdate({...state,languages:{...state.languages,[challenge.id]:nextLanguage},drafts:shouldReplace&&challenge.coding?{...state.drafts,[challenge.id]:challenge.coding.starterCode[nextLanguage]}:state.drafts})}
  async function execute(){if(!challenge.coding||!answer.trim())return;setRunning(true);const result=await runCode(challenge,language,answer);onUpdate({...state,codeRuns:{...state.codeRuns,[challenge.id]:[...runs,result]}});setRunning(false)}
  function submit(event:FormEvent){event.preventDefault();if(!answer.trim())return;const objectiveCorrect=challenge.type==='multiple-choice'?Number(answer)===challenge.correctOption:undefined;const attempt={challengeId:challenge.id,answer,objectiveCorrect,completedAt:new Date().toISOString()};const attempts=[...state.attempts.filter((item)=>item.challengeId!==challenge.id),attempt];const xpGain=previous?0:objectiveCorrect===false?10:25;onUpdate({...state,attempts,xp:state.xp+xpGain,currentChallengeIndex:index+1})}
  return <main className="shell diagnostic-shell"><button className="back" onClick={onExit}>← Dashboard</button><div className="diagnostic-progress"><span>Challenge {index+1} of {diagnosticChallenges.length}</span><div className="progress"><i style={{width:`${((index+1)/diagnosticChallenges.length)*100}%`}}/></div><span>{state.xp} XP</span></div><section className="card challenge-card"><div className="challenge-meta"><span>{challenge.type}</span>{challenge.skills.map((skill)=><span key={skill}>{skill}</span>)}</div><h1>{challenge.title}</h1><p className="scenario">{challenge.scenario}</p><h3>{challenge.prompt}</h3><DiagnosticInput challenge={challenge} answer={answer} setAnswer={setAnswer} language={language} setLanguage={setLanguage} running={running} onRun={execute} runs={runs}/><TutorPanel challenge={challenge} answer={answer} state={state} onUpdate={onUpdate}/><div className="evidence"><b>What this is testing</b><span>{challenge.evidence}</span></div><form onSubmit={submit}><button disabled={!answer.trim()}>{index===diagnosticChallenges.length-1?'Finish diagnostic':'Submit & continue'}</button></form></section></main>
}
function DiagnosticInput({challenge,answer,setAnswer,language,setLanguage,running,onRun,runs}:{challenge:Challenge;answer:string;setAnswer:(value:string)=>void;language:CodeLanguage;setLanguage:(language:CodeLanguage)=>void;running:boolean;onRun:()=>void;runs:CodeRunResult[]}){if(challenge.type==='multiple-choice')return <div className="options">{challenge.options?.map((option,index)=><label className={answer===String(index)?'selected':''} key={option}><input type="radio" name={challenge.id} value={index} checked={answer===String(index)} onChange={(event)=>setAnswer(event.target.value)}/><span>{option}</span></label>)}</div>;if(challenge.type==='coding'&&challenge.coding){const latest=runs.at(-1);return <div className="code-workspace"><div className="code-toolbar"><label>Language<select value={language} onChange={(event)=>setLanguage(event.target.value as CodeLanguage)}>{challenge.coding.languages.map((item)=><option key={item} value={item}>{item}</option>)}</select></label><button type="button" className="run-button" disabled={running||!answer.trim()} onClick={onRun}>{running?'Running…':'▶ Run tests'}</button></div><textarea className="code-input" rows={17} value={answer} onChange={(event)=>setAnswer(event.target.value)} spellCheck={false}/>{latest&&<div className={`run-result ${latest.status}`}><div className="run-summary"><strong>{latest.status==='passed'?'All tests passed':latest.status}</strong><span>{latest.durationMs} ms</span></div>{latest.error&&<pre>{latest.error}</pre>}</div>}</div>}return <textarea rows={9} value={answer} placeholder={challenge.placeholder} onChange={(event)=>setAnswer(event.target.value)}/>} 
export default App
